### ISSUE TITLE
build issue on debian

### ISSUE THREAD

**Issue by emiliocb4** [Rajpratik71/Realtek-rtl8811AU_8812AU_8821AU_linux-source-code#3]
Building module:
cleaning build area...
'make'....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.0-0.bpo.5-amd64 (x86_64)
Consult /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/make.log for more information.

root@nas:~/Realtek-rtl8811AU_8812AU_8821AU_linux-source-code# more /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/make.log
DKMS make.log for rtl8812AU_8821AU_linux-1.0 for kernel 4.19.0-0.bpo.5-amd64 (x86_64)
Sat Jul 20 11:42:31 CEST 2019
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.19.0-0.bpo.5-amd64/build M=/var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build  modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-0.bpo.5-amd64'
  CC [M]  /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/core/rtw_cmd.o
In file included from /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/osdep_service.h:41:0,
                 from /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/core/rtw_cmd.c:22:
/var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/osdep_service_linux.h: In function ‘_init_timer’:
/var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/osdep_service_linux.h:254:8: error: ‘_timer {aka struct timer_list}’ has no member named ‘data’
  ptimer->data = (unsigned long)cntx;
        ^~
/var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/osdep_service_linux.h:255:2: error: implicit declaration of function ‘init_timer’ [-Werror=implicit-function-decl
aration]
  init_timer(ptimer);
  ^~~~~~~~~~
In file included from /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/drv_types.h:35:0,
                 from /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/core/rtw_cmd.c:22:
/var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/wifi.h: At top level:
/var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/wifi.h:963:0: warning: "IEEE80211_MAX_AMPDU_BUF" redefined
 #define IEEE80211_MAX_AMPDU_BUF 0x40

In file included from /usr/src/linux-headers-4.19.0-0.bpo.5-common/include/net/cfg80211.h:24:0,
                 from /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/osdep_service_linux.h:76,
                 from /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/osdep_service.h:41,
                 from /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/include/drv_types.h:32,
                 from /var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/core/rtw_cmd.c:22:
/usr/src/linux-headers-4.19.0-0.bpo.5-common/include/linux/ieee80211.h:1442:0: note: this is the location of the previous definition
 #define IEEE80211_MAX_AMPDU_BUF  0x100

cc1: some warnings being treated as errors
/usr/src/linux-headers-4.19.0-0.bpo.5-common/scripts/Makefile.build:308: recipe for target '/var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/core/rtw_cmd.o' failed
make[4]: *** [/var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build/core/rtw_cmd.o] Error 1
/usr/src/linux-headers-4.19.0-0.bpo.5-common/Makefile:1539: recipe for target '_module_/var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build' failed
make[3]: *** [_module_/var/lib/dkms/rtl8812AU_8821AU_linux/1.0/build] Error 2
Makefile:146: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-0.bpo.5-amd64'
Makefile:1049: recipe for target 'modules' failed
make: *** [modules] Error 2

please help.

thanks

**Comment by jbbandos** [comment]
I'm stuck here too, on mx linux. Following.
